apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-vault-pvc
  namespace: vault-stg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-stg