apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backup
  namespace: vault-stage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-stg